repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: detect-private-key
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        additional_dependencies: [toml]
        exclude: env.py
        args: ["--profile", "black", --line-length=79]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
      - id: mypy
        language_version: python3
        args:
          - --no-warn-unused-ignores
          - --no-strict-optional
          - --ignore-missing-imports
        additional_dependencies:
          - "sqlalchemy"
          - "types-PyYAML"
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        language_version: python3.9
        args: ["--line-length=79"]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      args: ["--max-line-length=99"]
      exclude: migrations
