name: CI first test
on:
  push:
    branches:
      - "*"

jobs:
  run_tests:
    strategy:
      matrix:
        poetry-version: ["1.1.13"]
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: "3.9"
      - name: Install poetry
        uses: abatilo/actions-poetry@v2.1.3
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: View poetry --help
        run: poetry --help
