name: CI first test
on:
  push:
    branches:
      - "*"

jobs:
  run_tests:
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: zero_db_test
        ports: ['5432:5432']
    strategy:
      matrix:
        poetry-version: ["1.1.13"]
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v1
        with:
          python-version: "3.9"
      - name: Install poetry
        uses: abatilo/actions-poetry@v2.1.3
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install Dependencies
        run: poetry install
      - name: Run tests
        env:
          DATABASE_URL: 'postgresql+asyncpg://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/zero_db_test'
        run: poetry run pytest .
